[package]
name = "nrf_blinky"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
nrf52840-hal = { version = "0.16", features = ["rt"] }
panic-halt = "0.2"

[profile.release]
opt-level = "s"